<?php

return [
    'TERMINOS_SI' => 'SI',
    'TERMINOS_EN_ESPERA'=>'EN ESPERA'
    'TERMINOS_NO' => 'NO',
    'CONSENTIMIENTO_NO' => 'NO'
    'CONSENTIMIENTO_EN ESPERA' => 'EN ESPERA'
    'CONSENTIMIENTO_SI' => 'SI'
    'CONSENTIMIENTO_COMPLETO' => 'completo'
    'CONSENTIMIENTO_LLAVE' => 'terminado'
];