<?php

return [
    'TIPO_A' => 'A',
    'TIPO_B' => 'B',
    'USUARIO_CONFIRMA' => 'SI',
    'USUARIO_ESPERA' => 'EN ESPERA',
    'USUARIO_NIEGA' => 'NO',
    'USUARIO_APLICA' => 'APLICA',
    'USUARIO_NO_APLICA' => 'NO APLICA',
    'USUARIO_COMPLETO' => 'completo',
    'USUARIO_LLAVE' => 'terminado', 
    'MENSAJE_ERROR_MODELO_NOT_FOUND' =>'No se puede procesar su solicitud. Contacte al administrador.',
    'USUARIO_CONSTESTO' =>'contesto_OK',
    'SECCION_CONFIRMA_ATENCION'=>'confirma-atencion',
    'SECCION_CONFIRMA_JEFE'=>'confirma-jefe',
    'SECCION_CONDICIONES_VIVIENDA'=>'condiciones-vivienda',
    'SECCION_CONDICIONES_EXTRA'=>'condiciones-extralaborales',
    'SECCION_ESTRES' => 'sintomas-estres',
    'SECCION_PERSONALIDAD' => 'personalidad',
    'SECCION_AFRONTAMIENTO_I'=> 'afrontamiento-seccion-I',
    'SECCION_AFRONTAMIENTO_II' => 'afrontamiento-seccion-II',
    'SECCION_AFRONTAMIENTO_III'=> 'afrontamiento-seccion-III',
    'SECCION_FIN_ENCUESTA' => 'fin-encuesta',
    'ID_SECCION_EXT_CONDICIONES_VIVIENDA' => 29,
    'ID_SECCION_EXT_CONDICIONES_EXTRALABORAL' => 30,
    'ID_SECCION_ESTRES' => 31,
    'ID_SECCION_AFRONTAMIENTO_I' => 35,
    'ID_SECCION_AFRONTAMIENTO_II' => 36,
    'ID_SECCION_AFRONTAMIENTO_III' => 37,
    'ID_SECCION_PERSONALIDAD' => 41
];